// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemadeTiquetess.src.shared.context;

#nullable disable

namespace SistemadeTiquetess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427044017_CreacionDeTablas")]
    partial class CreacionDeTablas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SistemadeTiquetess.src.modules.Aircrafts.infrastructure.Entity.AircraftEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Aircrafts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000030"),
                            Capacity = 180,
                            IsActive = true,
                            Manufacturer = "Airbus",
                            Model = "A320neo",
                            RegistrationNumber = "N123AB"
                        });
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.Airlines.infrastructure.Entity.AirlineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Airlines");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000010"),
                            Code = "AV",
                            IsActive = true,
                            Name = "Avianca"
                        });
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.Airports.Infrastructure.Entity.AirportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IataCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000020"),
                            City = "Bogotá",
                            Country = "Colombia",
                            IataCode = "BOG",
                            IsActive = true,
                            Name = "El Dorado"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000021"),
                            City = "Miami",
                            Country = "Estados Unidos",
                            IataCode = "MIA",
                            IsActive = true,
                            Name = "Miami International"
                        });
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.Countries.Infrastructure.Entity.CountryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Code = "CO",
                            IsActive = true,
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000002"),
                            Code = "US",
                            IsActive = true,
                            Name = "Estados Unidos"
                        });
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.CustomerContacts.Infrastructure.Entity.CustomerContactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerContacts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000090"),
                            CustomerId = new Guid("a1000000-0000-0000-0000-000000000080"),
                            Email = "maria.lopez@example.com",
                            IsActive = true,
                            PhoneNumber = "+57 300 1112233"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000091"),
                            CustomerId = new Guid("a1000000-0000-0000-0000-000000000081"),
                            Email = "juan.perez@example.com",
                            IsActive = true,
                            PhoneNumber = "+57 300 3334455"
                        });
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.Customers.Infrastructure.Entity.CustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000080"),
                            DocumentNumber = "CC-1234567",
                            FullName = "María López",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000081"),
                            DocumentNumber = "CC-7654321",
                            FullName = "Juan Pérez",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.FlightSegments.Infrastructure.Entity.SegmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DestinationAirportId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OriginAirportId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationAirportId");

                    b.HasIndex("FlightId");

                    b.HasIndex("OriginAirportId");

                    b.ToTable("Segments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000110"),
                            DestinationAirportId = new Guid("a1000000-0000-0000-0000-000000000021"),
                            FlightId = new Guid("a1000000-0000-0000-0000-000000000100"),
                            OriginAirportId = new Guid("a1000000-0000-0000-0000-000000000020")
                        });
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.FlightStatus.Infrastructure.Entity.StatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FlightStatuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000040"),
                            Name = "Programado"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000041"),
                            Name = "En vuelo"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000042"),
                            Name = "Aterrizado"
                        });
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.Flights.Infrastructure.Entity.FlightEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000100"),
                            FlightNumber = "AV0101",
                            StatusId = new Guid("a1000000-0000-0000-0000-000000000040")
                        });
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.PaymentMethods.Infrastructure.Entity.PaymentMethodEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000070"),
                            Name = "Tarjeta de crédito"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000071"),
                            Name = "Efectivo"
                        });
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.Payments.Infrastructure.Entity.PaymentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("PaymentMethodId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("ReservationId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000160"),
                            Amount = 350.00m,
                            PaymentDate = new DateTime(2026, 4, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethodId = new Guid("a1000000-0000-0000-0000-000000000070"),
                            ReservationId = new Guid("a1000000-0000-0000-0000-000000000140")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000161"),
                            Amount = 50.00m,
                            PaymentDate = new DateTime(2026, 4, 1, 11, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethodId = new Guid("a1000000-0000-0000-0000-000000000071"),
                            ReservationId = new Guid("a1000000-0000-0000-0000-000000000140")
                        });
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.ReservationPassengers.Infrastructure.Entity.ReservationPassengerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ReservationId");

                    b.ToTable("ReservationPassengers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000150"),
                            CustomerId = new Guid("a1000000-0000-0000-0000-000000000080"),
                            ReservationId = new Guid("a1000000-0000-0000-0000-000000000140"),
                            SeatNumber = "1A"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000151"),
                            CustomerId = new Guid("a1000000-0000-0000-0000-000000000081"),
                            ReservationId = new Guid("a1000000-0000-0000-0000-000000000140"),
                            SeatNumber = "1B"
                        });
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.Reservations.Infrastructure.Entity.ReservationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("FlightId");

                    b.HasIndex("StatusId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000140"),
                            CustomerId = new Guid("a1000000-0000-0000-0000-000000000080"),
                            FlightId = new Guid("a1000000-0000-0000-0000-000000000100"),
                            ReservationDate = new DateTime(2026, 4, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            StatusId = new Guid("a1000000-0000-0000-0000-000000000061")
                        });
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.ReservationsStatus.Infrastructure.Entity.ReservationStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ReservationStatuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000060"),
                            Name = "Pendiente"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000061"),
                            Name = "Confirmada"
                        });
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.SeatAssignments.Infrastructure.Entity.SeatAssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ReservationPassengerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ReservationPassengerId");

                    b.HasIndex("SeatId");

                    b.ToTable("SeatAssignments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000170"),
                            ReservationPassengerId = new Guid("a1000000-0000-0000-0000-000000000150"),
                            SeatId = new Guid("a1000000-0000-0000-0000-000000000120")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000171"),
                            ReservationPassengerId = new Guid("a1000000-0000-0000-0000-000000000151"),
                            SeatId = new Guid("a1000000-0000-0000-0000-000000000121")
                        });
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.SeatAvailability.Infrastructure.Entity.SeatAvailabilityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("SeatId");

                    b.ToTable("SeatAvailabilities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000130"),
                            FlightId = new Guid("a1000000-0000-0000-0000-000000000100"),
                            IsAvailable = false,
                            SeatId = new Guid("a1000000-0000-0000-0000-000000000120")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000131"),
                            FlightId = new Guid("a1000000-0000-0000-0000-000000000100"),
                            IsAvailable = true,
                            SeatId = new Guid("a1000000-0000-0000-0000-000000000121")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000132"),
                            FlightId = new Guid("a1000000-0000-0000-0000-000000000100"),
                            IsAvailable = true,
                            SeatId = new Guid("a1000000-0000-0000-0000-000000000122")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000133"),
                            FlightId = new Guid("a1000000-0000-0000-0000-000000000100"),
                            IsAvailable = true,
                            SeatId = new Guid("a1000000-0000-0000-0000-000000000123")
                        });
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.Seats.Infrastructure.Entity.SeatEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000120"),
                            Class = "Economy",
                            Row = "1",
                            SeatNumber = "1A"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000121"),
                            Class = "Economy",
                            Row = "1",
                            SeatNumber = "1B"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000122"),
                            Class = "Economy",
                            Row = "2",
                            SeatNumber = "2A"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000123"),
                            Class = "Economy",
                            Row = "2",
                            SeatNumber = "2B"
                        });
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.TicketStatus.Infrastructure.Entity.TicketStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TicketStatuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000050"),
                            Name = "Emitido"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000051"),
                            Name = "Cancelado"
                        });
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.Tickets.Infrastructure.Entity.TicketEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ReservationPassengerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ReservationPassengerId");

                    b.HasIndex("StatusId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000180"),
                            IssueDate = new DateTime(2026, 4, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            ReservationPassengerId = new Guid("a1000000-0000-0000-0000-000000000150"),
                            StatusId = new Guid("a1000000-0000-0000-0000-000000000050"),
                            TicketNumber = "TK-BOG-MIA-0001"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000181"),
                            IssueDate = new DateTime(2026, 4, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            ReservationPassengerId = new Guid("a1000000-0000-0000-0000-000000000151"),
                            StatusId = new Guid("a1000000-0000-0000-0000-000000000050"),
                            TicketNumber = "TK-BOG-MIA-0002"
                        });
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.CustomerContacts.Infrastructure.Entity.CustomerContactEntity", b =>
                {
                    b.HasOne("SistemadeTiquetess.src.modules.Customers.Infrastructure.Entity.CustomerEntity", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.FlightSegments.Infrastructure.Entity.SegmentEntity", b =>
                {
                    b.HasOne("SistemadeTiquetess.src.modules.Airports.Infrastructure.Entity.AirportEntity", "DestinationAirport")
                        .WithMany()
                        .HasForeignKey("DestinationAirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemadeTiquetess.src.modules.Flights.Infrastructure.Entity.FlightEntity", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemadeTiquetess.src.modules.Airports.Infrastructure.Entity.AirportEntity", "OriginAirport")
                        .WithMany()
                        .HasForeignKey("OriginAirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DestinationAirport");

                    b.Navigation("Flight");

                    b.Navigation("OriginAirport");
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.Flights.Infrastructure.Entity.FlightEntity", b =>
                {
                    b.HasOne("SistemadeTiquetess.src.modules.FlightStatus.Infrastructure.Entity.StatusEntity", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.Payments.Infrastructure.Entity.PaymentEntity", b =>
                {
                    b.HasOne("SistemadeTiquetess.src.modules.PaymentMethods.Infrastructure.Entity.PaymentMethodEntity", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemadeTiquetess.src.modules.Reservations.Infrastructure.Entity.ReservationEntity", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentMethod");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.ReservationPassengers.Infrastructure.Entity.ReservationPassengerEntity", b =>
                {
                    b.HasOne("SistemadeTiquetess.src.modules.Customers.Infrastructure.Entity.CustomerEntity", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemadeTiquetess.src.modules.Reservations.Infrastructure.Entity.ReservationEntity", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.Reservations.Infrastructure.Entity.ReservationEntity", b =>
                {
                    b.HasOne("SistemadeTiquetess.src.modules.Customers.Infrastructure.Entity.CustomerEntity", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemadeTiquetess.src.modules.Flights.Infrastructure.Entity.FlightEntity", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemadeTiquetess.src.modules.ReservationsStatus.Infrastructure.Entity.ReservationStatusEntity", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Flight");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.SeatAssignments.Infrastructure.Entity.SeatAssignmentEntity", b =>
                {
                    b.HasOne("SistemadeTiquetess.src.modules.ReservationPassengers.Infrastructure.Entity.ReservationPassengerEntity", "ReservationPassenger")
                        .WithMany()
                        .HasForeignKey("ReservationPassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemadeTiquetess.src.modules.Seats.Infrastructure.Entity.SeatEntity", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReservationPassenger");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.SeatAvailability.Infrastructure.Entity.SeatAvailabilityEntity", b =>
                {
                    b.HasOne("SistemadeTiquetess.src.modules.Flights.Infrastructure.Entity.FlightEntity", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemadeTiquetess.src.modules.Seats.Infrastructure.Entity.SeatEntity", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("SistemadeTiquetess.src.modules.Tickets.Infrastructure.Entity.TicketEntity", b =>
                {
                    b.HasOne("SistemadeTiquetess.src.modules.ReservationPassengers.Infrastructure.Entity.ReservationPassengerEntity", "ReservationPassenger")
                        .WithMany()
                        .HasForeignKey("ReservationPassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemadeTiquetess.src.modules.TicketStatus.Infrastructure.Entity.TicketStatusEntity", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReservationPassenger");

                    b.Navigation("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
